NDefines.NCountry.VICTORY_CARD_DECAY_MONTHS = 120
NDefines.NCountry.VICTORY_CARD_INCREASE_MONTHS = 120
NDefines.NCountry.VICTORY_CARD_START_YEAR = 1450
NDefines.NCountry.VICTORY_CARD_START_OFFSET = 50
NDefines.NCountry.VICTORY_CARD_BONUS_SCORE = 500